### PR TITLE
Chore remove markdown

### PR DESCRIPTION
**Pull request by dybi**
resolves: #374

### CODE REVIEW

**Comment by rwrzesien** [comment]
@dybi Looks good, however the issue mentions data migration to remove markdown from current data (I am wondering if this is even possible without some super complex regex). Are you planning to do this or are you skipping this on purpose? Whatever you have chosen, please just drop a comment.

**Comment by dybi** [comment]
@rwrzesien 
> Btw. what about clickable hyperlinks?

quite frankly I forgot about this ;) I will add them

When it comes to migration, I am wondering how much of it (markdown) is in the current data. I think it should be checked first and then the decision should be made whether it is worth to implement ;)

**Comment by dybi** [comment]
Added hyperlinks in blue

**Comment by rwrzesien** [comment]
> When it comes to migration, I am wondering how much of it (markdown) is in the current data. I think it should be checked first and then the decision should be made whether it is worth to implement ;)

I think it won't be possible to cover all cases (or the migration doing this would be overkill).

Btw. interesting solution for those links :+1:

**Comment by dybi** [comment]
@kbeker @rwrzesien: migrations are solved in: https://github.com/Code-Poets/sheetstorm/pull/457

**Pull request merged**
